# Generated by Django 3.0 on 2021-02-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='counting',
            field=models.BooleanField(default=False),
        ),
    ]
