# Generated by Django 3.0 on 2021-02-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0004_auto_20210227_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='urna',
        ),
        migrations.AddField(
            model_name='urna',
            name='votos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='votacion.Voto'),
        ),
    ]
