# Generated by Django 3.0 on 2021-02-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0006_auto_20210227_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='urna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacion.Urna'),
        ),
    ]
