# Generated by Django 3.0 on 2021-02-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padron', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
